backend:
  name: github
  repo: AnaisLT/gatsby-blog
  
media_folder: static/assets
public_folder: assets
  
collections:
  - name: "posts"
    label: Posts
    folder: "src/pages/posts"
    description: "Blog posts about sustainability, health and fitness, healthy eating..."
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: author, label: Author, widget: string }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }